ALTER TABLE SYKMELDING_IDS
    ALTER COLUMN varsling_id TYPE uuid USING varsling_id::uuid;

ALTER TABLE SYKMELDING_IDS
    ADD FOREIGN KEY (varsling_id)
        REFERENCES PLANLAGT_VARSEL (uuid) ON DELETE CASCADE;
