apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: varsel-planlegging
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 20
    replication: 3
    retentionBytes: -1  # Messages will never be deleted because of disk space
    retentionHours: -1  # Messages will never be timed out
  acl:
    - team: team-esyfo
      application: esyfovarsel-planlegging
      access: read
    - team: team-esyfo
      application: syfomotebehov
      access: write
